locators:
  inclusions:
    - mode: ''
      value: ''
      index: 0
      uses: 0
  exclusions:
    - mode: ''
      value: ''
      index: 0
      uses: 0
actions:
  - verb: ''
    name: ''
    locators:
      - mode: ''
        value: ''
        index: 0
        uses: 0
  - verb: click
    name: menu
    locators:
      - mode: ''
        value: ''
        index: 0
        uses: 0
      - mode: text
        value: Menu
        index: 0
        uses: -1
      - mode: text
        value: Menu
        index: 0
        uses: -1
      - mode: text
        value: menu
        index: 0
        uses: -1
      - mode: value
        value: Menu
        index: 0
        uses: -1
      - mode: value
        value: Menu
        index: 0
        uses: -1
      - mode: value
        value: menu
        index: 0
        uses: -1
      - mode: aria-label
        value: Main navigation menu
        index: 0
        uses: 1
  - verb: click
    name: log_in
    locators:
      - mode: ''
        value: ''
        index: 0
        uses: 0
      - mode: text
        value: Log In
        index: 0
        uses: -1
      - mode: text
        value: Log in
        index: 0
        uses: 1
      - mode: text
        value: log in
        index: 0
        uses: 0
      - mode: value
        value: Log In
        index: 0
        uses: 0
      - mode: value
        value: Log in
        index: 0
        uses: 0
      - mode: value
        value: log in
        index: 0
        uses: 0
